package hr.algebra;

import hr.algebra.dal.MovieRepository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.models.Actor;
import hr.algebra.models.Director;
import hr.algebra.models.Genre;
import hr.algebra.models.Movie;
import hr.algebra.models.MovieArchive;
import hr.algebra.view.ActorsRefreshable;
import hr.algebra.view.MoviesRefreshable;
import hr.algebra.view.UserActorPanel;
import hr.algebra.view.UserMoviePanel;
import java.sql.SQLException;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author vitom
 */
public class UserFrame extends javax.swing.JFrame implements ActorsRefreshable,MoviesRefreshable{

    /**
     * Creates new form UserFrame
     */
     private MovieRepository repository;

    UserActorPanel userActorPanel;
    UserMoviePanel userMoviePanel;
    private MovieArchive movieArchive;
    private DefaultListModel<String> moviesModel; 

    
    private List<Movie> movies;
        private Set<Actor> actors;
    private Set<Director> directors;
    private Set<Genre> genres;

    public UserFrame() {
        initComponents();
        
         try {
             init();
             initTabs();
         } catch (SQLException ex) {
             Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
         } catch (Exception ex) {
             Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProfile = new javax.swing.JMenu();
        miLogOut = new javax.swing.JMenuItem();
        menuDownload = new javax.swing.JMenu();
        miXMLDownload = new javax.swing.JMenuItem();
        debugButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuProfile.setText("Profile");

        miLogOut.setText("Log out");
        menuProfile.add(miLogOut);

        jMenuBar1.add(menuProfile);

        menuDownload.setText("Download");

        miXMLDownload.setText("XML download");
        menuDownload.add(miXMLDownload);

        debugButton.setText("debugButton");
        debugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugButtonActionPerformed(evt);
            }
        });
        menuDownload.add(debugButton);

        jMenuBar1.add(menuDownload);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugButtonActionPerformed
        // TODO add your handling code here:
        MovieArchive test=movieArchive;
        System.out.println("ss");
    }//GEN-LAST:event_debugButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem debugButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDownload;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenuItem miXMLDownload;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables

    private void initTabs() {
        userActorPanel=new UserActorPanel(movies);
        userMoviePanel=new UserMoviePanel(movies,actors,directors,genres);
        tabPane.add("Movies",userMoviePanel);
        tabPane.add("Actors",userActorPanel);

        
    }

    private void loadMovies() {
       
    }

    private void init() throws SQLException, Exception {
                 repository = RepositoryFactory.getMovieRepository();
                 movies=repository.getMovies();
                 actors=repository.getActors();
                 directors=repository.getDirectors();
                 genres=repository.getGenres();
    //             movieArchive=repository.getMovieData();
                 System.out.println("ss");

    }

    @Override
    public void refreshActors() {
         try {
             actors=repository.getActors();
             userMoviePanel.setAllActors(actors);
             userActorPanel.setAllActors(actors);
         } catch (SQLException ex) {
             Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    @Override
    public void refreshMovies() {
         try {
             movies=repository.getMovies();
             userMoviePanel.setAllMovies(movies);
             userActorPanel.setAllMovies(movies);
         } catch (SQLException ex) {
             Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
}
